// Usage in Lancamentos.tsx (or ContasPagar.tsx / ContasReceber.tsx):
// import { gerarLancamentosRecorrentes } from '@/lib/recurrence';
// const parcelas = gerarLancamentosRecorrentes(novoLancamento, 'contas_pagar');
// for (const parcela of parcelas) { await supabase.from('contas_pagar').insert(parcela); }

type TipoRecorrencia = 'nenhuma' | 'mensal' | 'bimestral' | 'trimestral' | 'semestral' | 'anual';

type TableName = 'contas_pagar' | 'contas_receber';

/**
 * Record shape expected by the generator. Uses a loose type so it works
 * with both typed Supabase rows and ad-hoc form objects that pages build
 * before inserting (which often carry extra fields like qtd_recorrencia
 * and origem_lancamento that aren't yet in the generated types).
 */
interface RecurrenceRecord {
  recorrencia: TipoRecorrencia;
  vencimento: string;           // YYYY-MM-DD
  competencia: string;          // YYYY-MM
  parcela_atual?: number | null;
  total_parcelas?: number | null;
  qtd_recorrencia?: number | null;
  [key: string]: unknown;       // allow any other fields to pass through
}

// ---------------------------------------------------------------------------
// Pure helpers
// ---------------------------------------------------------------------------

/**
 * Maps a recurrence type to the number of months between occurrences.
 */
export function getRecurrenceMonths(recorrencia: string): number {
  const map: Record<string, number> = {
    mensal: 1,
    bimestral: 2,
    trimestral: 3,
    semestral: 6,
    anual: 12,
  };
  return map[recorrencia] ?? 0;
}

/**
 * Adds `months` months to a date string in YYYY-MM-DD format.
 * Clamps the day to the last valid day of the target month so that,
 * for example, 2025-01-31 + 1 month = 2025-02-28.
 */
export function incrementDate(dateStr: string, months: number): string {
  const [year, month, day] = dateStr.split('-').map(Number);
  const totalMonths = (year * 12 + (month - 1)) + months;
  const newYear = Math.floor(totalMonths / 12);
  const newMonth = (totalMonths % 12) + 1;

  // Clamp day to last day of new month
  const lastDay = new Date(newYear, newMonth, 0).getDate();
  const newDay = Math.min(day, lastDay);

  const mm = String(newMonth).padStart(2, '0');
  const dd = String(newDay).padStart(2, '0');
  return `${newYear}-${mm}-${dd}`;
}

/**
 * Adds `months` months to a competencia string in YYYY-MM format.
 */
export function incrementCompetencia(comp: string, months: number): string {
  const [year, month] = comp.split('-').map(Number);
  const totalMonths = (year * 12 + (month - 1)) + months;
  const newYear = Math.floor(totalMonths / 12);
  const newMonth = (totalMonths % 12) + 1;

  const mm = String(newMonth).padStart(2, '0');
  return `${newYear}-${mm}`;
}

// ---------------------------------------------------------------------------
// Main generator
// ---------------------------------------------------------------------------

/**
 * Given a record whose `recorrencia` is not 'nenhuma', generates an array of
 * cloned records with incremented dates, ready to be inserted into the DB.
 *
 * The original record is treated as parcela 1 (already saved by the caller).
 * This function returns parcelas 2 through N.
 *
 * @param record  The original (first) record, already inserted or about to be.
 * @param _table  Which table the records belong to (reserved for future use).
 * @returns       Array of new records ready for insertion.
 */
export function gerarLancamentosRecorrentes(
  record: RecurrenceRecord,
  _table: TableName,
): Record<string, unknown>[] {
  const { recorrencia } = record;

  if (!recorrencia || recorrencia === 'nenhuma') {
    return [];
  }

  const monthsPerInterval = getRecurrenceMonths(recorrencia);
  if (monthsPerInterval === 0) {
    return [];
  }

  // Determine how many *additional* entries to create (original is #1).
  const count = (record.qtd_recorrencia ?? record.total_parcelas ?? 12) as number;
  const totalToGenerate = Math.max(count - 1, 0); // parcela 1 already exists

  // Fields that must NOT be copied to the clones
  const excludedKeys = new Set(['id', 'created_at', 'updated_at']);

  const base: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(record)) {
    if (!excludedKeys.has(key)) {
      base[key] = value;
    }
  }

  const results: Record<string, unknown>[] = [];

  for (let i = 1; i <= totalToGenerate; i++) {
    const clone = { ...base };

    // Increment dates
    clone.vencimento = incrementDate(record.vencimento, monthsPerInterval * i);
    clone.competencia = incrementCompetencia(record.competencia, monthsPerInterval * i);

    // Parcela numbering: original is 1, clones are 2, 3, ...
    clone.parcela_atual = (record.parcela_atual ?? 1) + i;
    clone.total_parcelas = count;

    // Always start as pendente and mark as generated by recurrence
    clone.status = 'pendente';
    clone.origem_lancamento = 'recorrencia';

    // Clear payment-specific fields that don't apply to future entries
    clone.data_pagamento = null;
    clone.aprovado_em = null;
    clone.aprovado_por = null;
    clone.observacao_aprovacao = null;

    results.push(clone);
  }

  return results;
}
